config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenses
 
get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/moon', to: 'application#moon', as: 'moon'
  get '/sun', to: 'application#sun', as: 'sun'
  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :expenses, dependent: :destroy
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  validates :name, presence: { message: 'This field can not be empty' }
  validates :description, presence: { message: 'This field can not be empty' }
  validates :amount,
            numericality: { only_integer: true, greater_than_or_equal_to: 0,
                            message: 'The input should be greater or equal to 0' }



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses, foreign_key: 'user_id', class_name: 'Expense', dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end

  def moon
    cookies[:moon] = {
      value: 'dark mode on'
    }
    redirect_to root_path
  end

  def sun
    cookies.delete(:moon)
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories.all
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @expenses = current_user.expenses
    @categories = current_user.categories
  end

  def show
    @expense = current_user.expenses.find(params[:id])
  end

  def new
    @expense = Expense.new
  end

  def create
    expense = current_user.expenses.new(expense_params)
    if expense.save
      redirect_to root_path
      flash[:success] = 'The expense was saved successfully!'
    else

      redirect_to root_path
    end
  end

  def destroy
    @expense = current_user.expenses.find(params[:id])
    @expense.destroy
    flash[:success] = 'The expense was deleted successfully!'
    redirect_to root_path
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def update
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :description, :amount, :category, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def new
    super
  end

  def create
    super
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  def new
    super
    flash[:notice] = "Welcome to the site!"
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
    redirect_to root_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/expenses/_expenses.html.erb
  <div class="total-expense">
  <p>Total expenses: <span>$<%= current_user.expenses.sum(:amount) %>
  </span> </p>
  
  </div>
     
<section class="expenses-empty" >
  <% if current_user.expenses.empty? %>
    <p>
      You have no expenses yet
    </p>
    <%= button_to "Add expense" , "/expenses/new", data: { turbo_frame: 'modal' },  :method => :get, class:%>
  <% else %>
    <section class="expenses">
      <div class="add-expense">
        <h2>
          Your expenses
        </h2>
        <div class="add">
          <%= button_to "Add expense" , "/expenses/new", data: { turbo_frame: 'modal' }, :method => :get ,class: "add-expense-btn"%>
        </div>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>
              Name
            </th>
            <th>
              Amount
            </th>
            <th>
              Description
            </th>
            <th>
              Category
            </th>
            <th>
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          <% current_user.expenses.each do |expense| %>
            <tr>
              <td>
                <%= expense.name %>
              </td>
              <td>
                $<%= expense.amount %>
              </td>
              <td>
                <%= expense.description %>
              </td>
              <td>
                <% if expense.category  == "Food" %>
                  <%= image_tag  ("food.png"), class:'icon-food'  %>
                <% elsif expense.category  == "Transportation"  %>
                  <%= image_tag  ("Transportation.png"), class:'icon-trans'  %>
                <% elsif expense.category  == "Car"  %>
                  <%= image_tag  ("Car.png"), class:'icon-car'  %>
                <% elsif expense.category  == "Housing"  %>
                  <%= image_tag  ("Housing.png") , class:'icon-house' %>
                <% elsif expense.category  == "Cellphone"  %>
                  <%= image_tag  ("Cellphone.png") , class:'icon-cell' %>
                <% elsif expense.category  == "Entertainment"  %>
                  <%= image_tag  ("Entertainment.png"), class:'icon-ent'  %>
                <% elsif expense.category  == "Clothing"  %>
                  <%= image_tag  ("Clothing.png"), class:'icon-cloth'  %>
                <% elsif expense.category  == "Health"  %>
                  <%= image_tag  ("Health.png"), class:'icon-health'  %>
                <% elsif expense.category  == "Education"  %>
                  <%= image_tag  ("Education.png"), class:'icon-edu'  %>
                <% elsif expense.category  == "Travel"  %>
                  <%= image_tag  ("Travel.png"), class:'icon-travel'  %>
                <% elsif expense.category  == "Creditcards"  %>
                  <%= image_tag  ("Creditcards.png"), class:'icon-credit'  %>
                <% elsif expense.category  == "Other"  %>
                  <%= image_tag  ("Other.png"), class:'icon-other'  %>
                <%end%>
              </td>
              <td>
                <%= button_to "Delete", "/expenses/#{expense.id}", method: :delete, data: { confirm: "Are you sure?" }, class: "delete-btn" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
  <%end%>
</section>

app/views/expenses/index.html.erb
<h1>
All expenses
</h1>

app/views/expenses/new.html.erb
<%= turbo_frame_tag "modal" do %>
<%= form_with model: @expense, url: expenses_path  do |f| %>
<div class="modal">
  <p>
     <%= f.label :category %><br>
     <%= f.select :category, Category.all.collect { |c| [ c.name ] }, include_blank: true %>
    </p>
  

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
    </p>
  

 
  <p>
    <%= f.submit %>
  </p>
   <div>
      <%= button_tag "Cancel",  data: {
        controller: "modal",
        action: "modal#close",
      }, class: "cancel-button" %>
    </div>
</div>

<% end %>
<% end %>

app/views/expenses/show.html.erb
<h1>
    Show
</h1>
<%= link_to "Go back",  root_path%>

app/views/home/index.html.erb
<div class="flashes">
  <% flash.each do |name,value|%>
    <%if value == "Signed out successfully."%>
      <div class="out-flash">
        <p  class="signing-out">
          <%= value %>
        </p>
      </div>
    <%else%>
      <p class="signing-in" >
        <%= value %>
      </p>
    <%end%>
  <% end %>
</div>
<div>
  <% if user_signed_in?%>
    <div class="user-welcome">
      <p>
        Hello <%= current_user.name %>! 
      </p>
    </div>
  <%else%>
    <div class="welcome-users">
    <p> Please
      <%=link_to " Log in ", new_user_session_path ,class:'links' %>
      or
        <%=link_to " Sign up ", new_user_registration_path, class:'links' %>
        to start tracking your expenses
      </p>
    <%end%>
  </div>
  <main class="home-container">
    <div class="title-welcome">
      <h1 class="welcome">
        Welcome to Expense Tracker
      </h1>
    </div>
    <% if user_signed_in?%>
      <%= render "expenses/expenses" %>
    <%end%>
  </main>

app/views/layouts/_navbar.html.erb
<section>
  <nav class="navbar">
    <div class="icon" >
      <%= image_tag("money.png", style: 'height:4.8vw;width:4.8vw; margin: 5px;')%> <span>Expense Tracker</span>
    </div>
    <% if user_signed_in?%>
      <div class="sign-out">
        <%=button_to "Sign out", destroy_user_session_path, method: :delete,class:"sign-out-btn" %>
      </div>
    <% else %>
      <div class="log-in">
        <%= link_to "Login",  new_user_session_path ,class:"log-in-btn"   %>
      </div>
      <div class="sign-up" >
        <%= link_to "Sign up",  new_user_registration_path, class:"sign-up-btn" %>
      </div>
    <% end %>
    <% if cookies[:moon] %>
      <div class="toggles">
        <%= link_to  image_tag("sun.png", class:"logo"), sun_path, method: :get%>
      </div>
    <% else %>
      <div class="toggles">
        <%= link_to image_tag("moon.png", class:"logo"), moon_path, method: :get%>
      </div>
    <% end %>
  </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expense tracker</title>
     <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <% if cookies[:moon] %>
        <%= stylesheet_link_tag 'application_dark', media: 'all', 'data-turbolinks-track': 'reload' %>
      <% else %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
       <% end %>

   
</head>


  <body  >
    <%= render "layouts/navbar" %>
    <main class="main" >
     <%= turbo_frame_tag "modal" %>
      <%= yield %>
    </main>
  </body>
</html>